---
title: "Amberson Election Status"
author: "Jonathan Cervas"
affiliation: 
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
bibliography: 
biblio-style: apsr
geometry: margin=1in
fontsize: 11pt
# spacing: double
endnote: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r function-units}
# Function to print units by row based on the first digit
print_units_by_row <- function(units) {
  first_digits <- unique(floor(units / 100))
  for (digit in first_digits) {
    # Using paste with collapse="," to add commas between numbers
    cat(paste(units[floor(units / 100) == digit], collapse=", "), "\n")
  }
}
```

```{r directory}
directory <- '/Users/cervas/Downloads/'

emails <- read.csv("https://raw.githubusercontent.com/jcervas/amberson/refs/heads/main/amberson-emails.csv")

# unitWeights <- read.csv('https://raw.githubusercontent.com/jcervas/amberson/refs/heads/main/unit-weights.csv')
```

```{r}
registration <- read.table(paste0(directory, "voter_emails.txt"), header=F, sep=",")
names(registration) <- c("Email", "Weight")

registration <- merge(registration,emails, by=c("Email", "Weight"), all=T)
head(registration)
```

```{r read-OpaVote}
# Read OpaVote Files
voted <- read.table(paste0(directory, "voted.txt"))
voted$voted <- 1

not_voted <- read.table(paste0(directory, 'not_voted.txt'))
not_voted$not_voted <- 1

# Exclude those who are disabled (not usual)
disabled_voted <- read.table(paste0(directory, 'disabled.txt'))
disabled_voted$disabled <- 1
```

```{r merge-files}
# Registration and Voted
voted_merge <- merge(registration,voted, by.x="Email",by.y="V1", all=T)
units_voted <- sort(voted_merge$Unit[voted_merge$voted %in% 1])
units_voted_weight <- sort(voted_merge$Weight[voted_merge$voted %in% 1])

votes_cast <- sum(voted_merge$Weight[voted_merge$voted %in% 1])
votes_total <- sum(emails$Weight)
cat("Reached Quorum? ",
votes_cast/votes_total)

# Not voted
voted_notvoted_merge <- merge(voted_merge,not_voted, by.x="Email", by.y="V1", all=T)

# Disabled
voted_notvoted_disabled_merge <- merge(voted_notvoted_merge,disabled_voted, by.x="Email", by.y="V1", all.x=T)

# Sort
units_notvoted <- sort(voted_merge$Unit[!voted_merge$voted %in% 1])

units_notvoted <- sort(voted_notvoted_disabled_merge$Unit[is.na(voted_notvoted_disabled_merge$disable) & is.na(voted_notvoted_disabled_merge$voted)])

# Visited OpaVote?
# visited <- read.table('/Users/cervas/Library/Mobile Documents/com~apple~CloudDocs/Downloads/visited.txt')
# visited$visited <- 1
# voted_notvoted_disabled_visited_merge <- merge(voted_notvoted_disabled_merge,visited, by.x="Email", by.y="V1", all.x=T)
# sort(voted_notvoted_disabled_visited_merge$Unit[
#   (is.na(voted_notvoted_disabled_visited_merge$disable) & 
#    is.na(voted_notvoted_disabled_visited_merge$voted)) & 
#   !is.na(voted_notvoted_disabled_visited_merge$visited)
# ])

```

# Number of voters
```{r voted-output}
sum(voted$voted)
```

# Unit Percentage (Weighted) voted"
```{r}
paste0(round(sum(voted_merge$Weight[voted_merge$voted %in% 1])/999989, d=3) * 100, "%")
```

# Units that have voted
```{r}
print_units_by_row(units_voted)
```

# Units that have not voted
```{r}
print_units_by_row(units_notvoted)
```







